import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=p=>readFileSync(new URL(p,import.meta.url),'utf8');
const engine=read('../app/core/typing-engine.js');
const ui=read('../app/main.js');
const css=read('../app/styles.css');
const config=read('../app/core/storage.js');
const check=(label,ok)=>{assert.ok(ok,label);console.log('✓ 2.6 contract: '+label);};
check('no fixed character-count scroll heuristic',!engine.includes('next%36'));
check('auto-follow actually occurs on every current-key update',engine.includes('if(this.followCursor)this._scheduleScroll(next)'));
check('typing viewport is scrollable, not clipped',/\.typing-text\{[^}]*overflow-y:auto!important/.test(css));
check('RTL glyph passage remains one uninterrupted text node',engine.includes('this.textNode=document.createTextNode(this.target)'));
check('typing navigation has five interactive controls', ['read-home','read-up','read-down','read-zoom-in','read-zoom-out','read-follow'].every(id=>ui.includes(`id="${id}"`)));
check('cold launch explicitly skips IndexedDB library query',ui.includes('fastStart?[]:await getCustomTextsCached()'));
check('native runtime diagnostics run after initial practice',ui.indexOf("await routeTo('practice',{fastStart:true})")<ui.lastIndexOf('loadRuntimeInfo().catch'));
check('heatmap never forces calculations via idle callback timeout',!ui.includes('loadHeatmap,{timeout:1200}'));
check('idle timer disposes on navigation',ui.includes('clearInterval(idleGuardian);cancelAnimationFrame(hintRaf)'));
check('idle control persists from settings',ui.includes("settings.idlePauseSeconds=Number(document.querySelector('#s-idle-pause').value)"));
check('readability zoom stored independently of language',config.includes('textScale:1'));
check('route guard stops stale completion dialogs',ui.includes('if(serial!==routeSerial || disposed)return;'));
